/* AUTO-GENERATED by tools/_export-s-alloys-player-lore.mjs — do not edit by hand. */
import type { GearKind } from './gearLayouts.js';

export interface GeneratedAlloyPlayerMeta {
  tier: number;
  tierBand: string;
  vanillaTier: string;
  craftNote: string;
  stats: {
    attackBonus: number;
    miningSpeedMult: number;
    durability: number;
    armor: number;
    toughness: number;
  };
  enchantability: number;
  passives: Partial<Record<GearKind, string[]>>;
  intrinsicByGear: Partial<Record<GearKind | 'default', string>>;
  defaultIntrinsic?: string;
  projectiles: Partial<Record<'bow' | 'crossbow', string>>;
}

export const GENERATED_ALLOY_PLAYER_META: Record<string, GeneratedAlloyPlayerMeta> = {
  "tin": {
    "tier": 1,
    "tierBand": "common",
    "vanillaTier": "copper",
    "craftNote": "3 copper ingots + clay",
    "stats": {
      "attackBonus": 0,
      "miningSpeedMult": 1.05,
      "durability": 180,
      "armor": 1,
      "toughness": 0
    },
    "enchantability": 13,
    "passives": {},
    "intrinsicByGear": {},
    "projectiles": {}
  },
  "bronze": {
    "tier": 2,
    "tierBand": "common",
    "vanillaTier": "copper",
    "craftNote": "3 copper ingots + 2 bricks",
    "stats": {
      "attackBonus": 0.5,
      "miningSpeedMult": 1.08,
      "durability": 220,
      "armor": 2,
      "toughness": 0
    },
    "enchantability": 13,
    "passives": {},
    "intrinsicByGear": {
      "pickaxe": "Unbreaking I",
      "shovel": "Unbreaking I",
      "axe": "Unbreaking I",
      "sword": "Unbreaking I, Sweeping Edge I",
      "hoe": "Unbreaking I",
      "bow": "Unbreaking I",
      "crossbow": "Unbreaking I, Piercing I",
      "helmet": "Unbreaking I",
      "chestplate": "Unbreaking I",
      "leggings": "Unbreaking I",
      "boots": "Unbreaking I",
      "default": "Unbreaking I"
    },
    "defaultIntrinsic": "Unbreaking I",
    "projectiles": {}
  },
  "silver": {
    "tier": 3,
    "tierBand": "uncommon",
    "vanillaTier": "iron",
    "craftNote": "2 iron ingots + coal + copper ingot",
    "stats": {
      "attackBonus": 0.5,
      "miningSpeedMult": 1.1,
      "durability": 300,
      "armor": 2.5,
      "toughness": 0
    },
    "enchantability": 14,
    "passives": {
      "helmet": [
        "While worn: Night vision"
      ],
      "boots": [
        "While worn: Swift step"
      ]
    },
    "intrinsicByGear": {
      "pickaxe": "Unbreaking I, Efficiency I, Silk Touch I",
      "shovel": "Unbreaking I, Efficiency I",
      "axe": "Unbreaking I, Smite I",
      "sword": "Unbreaking I, Smite I",
      "hoe": "Unbreaking I, Smite I",
      "bow": "Unbreaking I, Power I",
      "crossbow": "Unbreaking I, Piercing I",
      "helmet": "Unbreaking I",
      "chestplate": "Unbreaking I",
      "leggings": "Unbreaking I",
      "boots": "Unbreaking I"
    },
    "projectiles": {
      "bow": "Arrows: Spectral",
      "crossbow": "Arrows: Spectral"
    }
  },
  "steel": {
    "tier": 4,
    "tierBand": "uncommon",
    "vanillaTier": "iron",
    "craftNote": "2 iron ingots + 2 coal + brick",
    "stats": {
      "attackBonus": 1,
      "miningSpeedMult": 1.12,
      "durability": 400,
      "armor": 3,
      "toughness": 0.5
    },
    "enchantability": 14,
    "passives": {
      "chestplate": [
        "While worn: Resistance"
      ],
      "boots": [
        "While worn: Slow falling"
      ]
    },
    "intrinsicByGear": {
      "pickaxe": "Unbreaking II",
      "shovel": "Unbreaking II",
      "axe": "Unbreaking II",
      "sword": "Unbreaking II",
      "hoe": "Unbreaking II",
      "bow": "Unbreaking II",
      "crossbow": "Unbreaking II, Multishot I",
      "helmet": "Unbreaking II",
      "chestplate": "Unbreaking II",
      "leggings": "Unbreaking II",
      "boots": "Unbreaking II",
      "default": "Unbreaking II"
    },
    "defaultIntrinsic": "Unbreaking II",
    "projectiles": {}
  },
  "cobalt": {
    "tier": 5,
    "tierBand": "uncommon",
    "vanillaTier": "iron",
    "craftNote": "2 iron ingots + 2 lapis + coal — or 9 fragments",
    "stats": {
      "attackBonus": 1,
      "miningSpeedMult": 1.18,
      "durability": 500,
      "armor": 3.5,
      "toughness": 0.5
    },
    "enchantability": 15,
    "passives": {
      "pickaxe": [
        "While held: Haste"
      ],
      "helmet": [
        "While worn: Low-light vision"
      ]
    },
    "intrinsicByGear": {
      "pickaxe": "Unbreaking II, Efficiency I",
      "shovel": "Unbreaking II, Efficiency I",
      "axe": "Unbreaking II",
      "sword": "Unbreaking II",
      "hoe": "Unbreaking II",
      "bow": "Unbreaking II",
      "crossbow": "Unbreaking II, Quick Charge I",
      "helmet": "Unbreaking II",
      "chestplate": "Unbreaking II",
      "leggings": "Unbreaking II",
      "boots": "Unbreaking II"
    },
    "projectiles": {
      "crossbow": "Arrows: Slowness"
    }
  },
  "nickel": {
    "tier": 6,
    "tierBand": "rare",
    "vanillaTier": "iron",
    "craftNote": "2 iron ingots + gold ingot + copper ingot — or 9 fragments",
    "stats": {
      "attackBonus": 1.5,
      "miningSpeedMult": 1.15,
      "durability": 550,
      "armor": 4,
      "toughness": 1
    },
    "enchantability": 15,
    "passives": {
      "leggings": [
        "While worn: Absorption"
      ]
    },
    "intrinsicByGear": {
      "pickaxe": "Unbreaking II, Fortune I",
      "shovel": "Unbreaking II",
      "axe": "Unbreaking II, Sharpness I",
      "sword": "Unbreaking II, Sharpness I",
      "hoe": "Unbreaking II, Sharpness I",
      "bow": "Unbreaking II, Power I",
      "crossbow": "Unbreaking II, Piercing I",
      "helmet": "Unbreaking II, Thorns I",
      "chestplate": "Unbreaking II, Thorns I",
      "leggings": "Unbreaking II, Thorns I",
      "boots": "Unbreaking II, Thorns I"
    },
    "projectiles": {
      "bow": "Arrows: Poison"
    }
  },
  "platinum": {
    "tier": 7,
    "tierBand": "rare",
    "vanillaTier": "gold",
    "craftNote": "2 gold ingots + iron ingot + 2 amethyst",
    "stats": {
      "attackBonus": 2,
      "miningSpeedMult": 1.12,
      "durability": 600,
      "armor": 4.5,
      "toughness": 1
    },
    "enchantability": 22,
    "passives": {
      "pickaxe": [
        "While held: +1 Luck"
      ],
      "sword": [
        "While held: +1 Luck"
      ]
    },
    "intrinsicByGear": {
      "pickaxe": "Unbreaking III, Fortune I",
      "shovel": "Unbreaking III",
      "axe": "Unbreaking III, Sharpness I",
      "sword": "Unbreaking III, Sharpness I",
      "hoe": "Unbreaking III, Sharpness I",
      "bow": "Unbreaking III, Power II",
      "crossbow": "Unbreaking III, Multishot I, Quick Charge I",
      "helmet": "Unbreaking III, Protection I",
      "chestplate": "Unbreaking III, Protection I",
      "leggings": "Unbreaking III, Protection I",
      "boots": "Unbreaking III, Protection I"
    },
    "projectiles": {
      "crossbow": "Arrows: Wounding"
    }
  },
  "mythril": {
    "tier": 8,
    "tierBand": "epic",
    "vanillaTier": "diamond",
    "craftNote": "2 gold ingots + emerald + diamond — or 9 fragments",
    "stats": {
      "attackBonus": 2.5,
      "miningSpeedMult": 1.25,
      "durability": 1200,
      "armor": 5,
      "toughness": 1.5
    },
    "enchantability": 10,
    "passives": {
      "sword": [
        "While held: Strength"
      ],
      "chestplate": [
        "While worn: Fire resistance"
      ]
    },
    "intrinsicByGear": {
      "pickaxe": "Unbreaking III, Efficiency II",
      "shovel": "Unbreaking III, Efficiency II",
      "axe": "Unbreaking III, Sharpness II",
      "sword": "Unbreaking III, Sharpness II",
      "hoe": "Unbreaking III, Sharpness II",
      "bow": "Unbreaking III, Power II, Flame I, Infinity I",
      "crossbow": "Unbreaking III, Piercing II, Quick Charge I",
      "helmet": "Unbreaking III, Protection II",
      "chestplate": "Unbreaking III, Protection II",
      "leggings": "Unbreaking III, Protection II",
      "boots": "Unbreaking III, Protection II"
    },
    "projectiles": {
      "crossbow": "Bolts: Flaming"
    }
  },
  "adamantine": {
    "tier": 9,
    "tierBand": "legendary",
    "vanillaTier": "diamond",
    "craftNote": "2 iron ingots + 2 diamonds + echo shard — or 9 fragments",
    "stats": {
      "attackBonus": 3,
      "miningSpeedMult": 1.2,
      "durability": 1400,
      "armor": 5.5,
      "toughness": 2
    },
    "enchantability": 10,
    "passives": {
      "chestplate": [
        "While worn: Steadfast",
        "While worn: Resistance"
      ]
    },
    "intrinsicByGear": {
      "pickaxe": "Unbreaking III, Efficiency III, Fortune II",
      "shovel": "Unbreaking III, Efficiency III",
      "axe": "Unbreaking III, Sharpness III",
      "sword": "Unbreaking III, Sharpness III",
      "hoe": "Unbreaking III, Sharpness III",
      "bow": "Unbreaking III, Power III",
      "crossbow": "Unbreaking III, Piercing III",
      "helmet": "Unbreaking III, Protection II, Thorns I",
      "chestplate": "Unbreaking III, Protection II, Thorns I",
      "leggings": "Unbreaking III, Protection II, Thorns I",
      "boots": "Unbreaking III, Feather Falling II"
    },
    "projectiles": {
      "crossbow": "Bolts: Heavy"
    }
  },
  "astral": {
    "tier": 10,
    "tierBand": "mythic",
    "vanillaTier": "netherite",
    "craftNote": "8 diamonds around netherite scrap (shaped)",
    "stats": {
      "attackBonus": 3.5,
      "miningSpeedMult": 1.3,
      "durability": 2031,
      "armor": 6,
      "toughness": 3
    },
    "enchantability": 22,
    "passives": {
      "helmet": [
        "While worn: Water breathing"
      ],
      "chestplate": [
        "While worn: Regeneration"
      ],
      "leggings": [
        "While worn: Slow falling"
      ],
      "boots": [
        "While worn: Swift step"
      ]
    },
    "intrinsicByGear": {
      "pickaxe": "Unbreaking III, Efficiency IV, Fortune II",
      "shovel": "Unbreaking III, Efficiency IV",
      "axe": "Unbreaking III, Sharpness IV",
      "sword": "Unbreaking III, Sharpness IV",
      "hoe": "Unbreaking III, Sharpness IV",
      "bow": "Unbreaking III, Power IV, Flame I, Infinity I",
      "crossbow": "Unbreaking III, Quick Charge II, Piercing II",
      "helmet": "Unbreaking III, Protection III",
      "chestplate": "Unbreaking III, Protection III",
      "leggings": "Unbreaking III, Protection III",
      "boots": "Unbreaking III, Protection III"
    },
    "projectiles": {
      "bow": "Arrows: Spectral",
      "crossbow": "Arrows: Spectral"
    }
  }
} as const;
